# Generated by Django 3.2.4 on 2021-06-17 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaint',
            old_name='severity',
            new_name='urgency',
        ),
        migrations.AddField(
            model_name='complaint',
            name='location',
            field=models.CharField(default='Hostel', max_length=20),
        ),
    ]
